import json
import os
import subprocess
from pathlib import Path

import requests

GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
PR_NUMBER = os.environ["PR_NUMBER"]
REPO = os.environ["REPO"]

diff_text = Path("pr.diff").read_text(encoding="utf-8", errors="ignore")

if not diff_text.strip():
    review_text = "## AI Review Summary\n- No diff found for this PR."
else:
    prompt = f"""
你是资深代码审查员。请只指出“值得人工进一步确认”的问题，不要罗列格式、命名、排版问题。

重点关注：
1. 安全风险
2. 逻辑 bug
3. 边界条件
4. breaking change
5. 测试缺失
6. CI / workflow / deploy 风险

请输出中文 Markdown，格式如下：

## AI Review Summary
- 一句话总结这次改动
- 风险等级：低 / 中 / 高

## Questions
- 最多列出 3 个值得作者确认的问题
- 每条写清楚：
  - 文件
  - 风险点
  - 你想问作者的问题

如果没有明显问题，就写：
- 暂未发现明显高风险改动，建议人工快速检查关键逻辑和测试覆盖。

以下是 PR diff：

{diff_text[:90000]}
""".strip()

    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        f"models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
    )

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2
        }
    }

    resp = requests.post(url, json=payload, timeout=120)
    resp.raise_for_status()
    data = resp.json()

    try:
        review_text = data["candidates"][0]["content"]["parts"][0]["text"]
    except Exception:
        review_text = (
            "AI review failed to parse model output.\n\n```json\n"
            + json.dumps(data, ensure_ascii=False, indent=2)[:4000]
            + "\n```"
        )

body = f"""{review_text}

---
_Auto-generated by Gemini PR review workflow._
"""

subprocess.run(
    [
        "gh", "pr", "comment", PR_NUMBER,
        "--repo", REPO,
        "--body", body,
    ],
    check=True,
)